### ISSUE TITLE
logout method not working

### ISSUE THREAD

**Issue by uitlaber** [apstanisic/directus-dart#14]
Code
```
 final sdk = await Directus(config.API_URL).init();
  try {
    await sdk.auth.logout();
  } catch (e) {
    print(e);
  }
```
Send to url  POST  /auth/refresh    return status 401
But doesn't send anything POST /auth/logout

**Comment by uitlaber** [comment]
Oh anything not work after logout :)

**Comment by uitlaber** [comment]
remove .init() and working

**Comment by apstanisic** [comment]
`init()` is needed because it initializes the storage, and gets auth data, without it, auth won't work propely. 
It's calling `/auth/refresh` because there is a token that is expired, and it tries to fetch a new one. But it should unlock after getting new token, and finish logging out, so this is definitely a bug

**Comment by uitlaber** [comment]
my auth.dart  
```
import 'package:directus/directus.dart';
import 'package:meyirim/core/config.dart' as config;

Future<void> logout() async {
  if (await isLoggedIn()) {
    final sdk = await Directus(config.API_URL).init();
    await sdk.auth.logout();
  }
}

Future<void> login(String email, String password) async {
  final sdk = await Directus(config.API_URL).init();
  await sdk.auth.login(email: email, password: password);
}

Future<DirectusResponse<DirectusUser>> register(data) async {
  final sdk = await Directus(config.API_URL).init();
  final createdUser = sdk.users.createOne(DirectusUser.fromJson(data));
  return createdUser;
}

Future<bool> isLoggedIn() async {
  final sdk = await Directus(config.API_URL).init();
  bool result = sdk.auth.isLoggedIn;
  return result;
}
```
Or how to best way to add global sdk?   ``` final sdk = await Directus(config.API_URL).init();```

**Comment by uitlaber** [comment]
After logout 
```
I/flutter (18750): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (18750): Receiver: null
I/flutter (18750): Tried calling: statusCode
```
![photo_2021-01-21_10-24-21](https://user-images.githubusercontent.com/18505561/105279924-d7feec80-5bd2-11eb-89d7-de2f8402ca61.jpg)

**Comment by apstanisic** [comment]
You pass variable like any other, trough constructor, with provider, bloc... if that's what you're asking. 
Soon there will be singleton version, you can track progress in #12.
You should initialize sdk only once, then just use that variable:
```dart
final sdk = await Directus(url).init();

isLoggedIn() {
return  sdk.auth.isLoggedIn;
}

logout() {
sdk.auth.logout();
}

getData() {
  return sdk.items('data').readMany();
}
```

**Comment by uitlaber** [comment]
Maybe i'm on right way
```
lib/core/auth.dart:7:26: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
    print(sdk.auth.tokens!.accessToken);
```

**Comment by uitlaber** [comment]
found  https://github.com/directus/directus/commit/ff399f94b65b9766e0af7509df03aeb86ff91a07#diff-2e0966802490ef6b64754924c1f0da2807f05359551e77bf115ce40384d56e0f

**Comment by apstanisic** [comment]
This library is using null safety, so you have to have Dart version that has enabled nnbd. 
It's possible that error from the API is because of the bug that you linked, what version of directus are you using?

**Comment by uitlaber** [comment]
I used directus version  directus/directus:v9.0.0-rc.28 from docker

**Comment by uitlaber** [comment]
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_svg: ^0.19.2+1
  flutter_swiper: ^1.1.6
  intl: ^0.17.0-nullsafety.2
  cached_network_image: ^2.5.0
  page_transition: ^2.0.1-nullsafety.0
  youtube_player_flutter: ^7.0.0+7
  shared_preferences: ^0.5.12+4
  form_validator: ^0.1.7
  mask_text_input_formatter: ^1.2.1
  dio: ^3.0.10
  directus:
    git:
      url: https://github.com/apstanisic/directus-dart.git
  flutter:
    sdk: flutter
dependency_overrides:
  flutter_inappwebview: ^4.0.0+4
```
